### ISSUE TITLE
notusMarkdown.encode(_delta)  cannot handle Image

### ISSUE THREAD

**Issue by zfha** [memspace/zefyr#126] opened 2019-07-11 06:36 UTC
```
[VERBOSE-2:ui_dart_state.cc(148)] Unhandled Exception: Invalid argument(s): Cannot handle embed: {type: image, source: https://qgt-upload.oss-cn-hangzhou.aliyuncs.com/upload/POST_1562826649531}
#0      _NotusMarkdownEncoder._writeAttribute 
package:notus/…/convert/markdown.dart:172
#1      _NotusMarkdownEncoder._writeInline 
package:notus/…/convert/markdown.dart:152
#2      _NotusMarkdownEncoder.convert._handleSpan 
package:notus/…/convert/markdown.dart:65
#3      _NotusMarkdownEncoder.convert 
package:notus/…/convert/markdown.dart:87
#4      Codec.encode  (dart:convert/codec.dart:21:32)
#5      _WrappedEditorState.initState.<anonymous closure> 
package:youkeda_flutter/…/post_publish/editor.dart:70
#6      _rootRunUnary  (dart:async/zone.dart:1132:38)
#7      _CustomZone.runUnary  (dart:async/zone.dart:1029:19)
#8      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:931:7)
#9      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:336:11)
#10     _DelayedData.perform  (dart:async/stream_impl.dart:591:14)
#11     _StreamImplEvents.handleNext  (dart:async/stream_impl.dart:707:11)
#12     _PendingEvents.schedule.<anonymous closure>  (dart:async/stream_impl.dart:667:7)
#13     _rootRun  (dart:async/zone.dart:1120:38)
#14     _CustomZone.run  (dart:async/zone.dart:1021:19)
#15     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
#16     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
#17     _rootRun  (dart:async/zone.dart:1124:13)
#18     _CustomZone.run  (dart:async/zone.dart:1021:19)
#19     _CustomZone.runGuarded  (dart:async/zone.dart:923:7)
#20     _CustomZone.bindCallbackGuarded.<anonymous closure>  (dart:async/zone.dart:963:23)
#21     _microtaskLoop  (dart:async/schedule_microtask.dart:41:21)
#22     _startMicrotaskLoop  (dart:async/schedule_microtask.dart:50:5)
```

how to export markdown with image?

**Comment by pulyaevskiy** [comment] 2019-09-14 22:39
Closing this as duplicate of #166 . Please follow discussion there.

**Closed by pulyaevskiy** 2019-09-14 22:39 UTC
