### ISSUE TITLE
Old error happens

### ISSUE THREAD

**Issue by jinfagang** [memspace/zefyr#204] opened 2019-11-06 14:04 UTC
```
zefyr-0.8.0/lib/src/widgets/input.dart:11:7: Error: The
non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/Users/jintian/development/flutter/packages/flutter/lib/src/services/text_input.dart:658:8: Context:
'TextInputClient.connectionClosed' is defined here.
  void connectionClosed();
       ^^^^^^^^^^^^^^^^
```

**Comment by pulyaevskiy** [comment] 2019-11-07 22:08
Closing as duplicate of #205

**Closed by pulyaevskiy** 2019-11-07 22:08 UTC
