### ISSUE TITLE
is there any option in Editor to restrict number of lines while typing??

### ISSUE THREAD

**Issue by AteqEjaz** [memspace/zefyr#170] opened 2019-09-16 15:42 UTC
Hi,

 Is there maxLines property in the Editor to restrict number of lines while typing?

Thanks:)

**Comment by pulyaevskiy** [comment] 2019-09-17 03:52
Looks like duplicate of #50 . Closing this one, please make sure to follow discussion on the other issue.

**Closed by pulyaevskiy** 2019-09-17 03:52 UTC
