### ISSUE TITLE
Build error for Flutter zefyr@0.8.0

### ISSUE THREAD

**Issue by sibukkwebdigi** [memspace/zefyr#220] opened 2019-12-20 13:35 UTC
Trying to implement zefyer editor based on https://zefyr-editor.gitbook.io/docs/quick-start

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
org-dartlang-app:///packages/flutter/src/services/text_input.dart: Context:
'TextInputClient.connectionClosed' is defined here.
Error compiling dartdevc module:zefyr|lib/src/widgets/buttons.ddc.js
packages/zefyr/src/widgets/input.dart:11:7: Error: The non-abstract class
'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

**Comment by cgestes** [comment] 2019-12-20 14:17
This is a duplicate of https://github.com/memspace/zefyr/issues/210

**Comment by pulyaevskiy** [comment] 2020-01-10 05:23
Closing as duplicate.

**Closed by pulyaevskiy** 2020-01-10 05:23 UTC
