### ISSUE TITLE
NoSuchMethodError: NoSuchMethodError: The getter 'position' was called on null.

### ISSUE THREAD

**Issue by Panthro** [memspace/zefyr#67] opened 2019-01-07 22:25 UTC
## Steps to Reproduce

Tab bar with zefyr as one of the children, when scrolling in/out before zefyr is fully loaded this error is logged.

The code has already changed in master from the published version (0.3.0) which I'm using, the actual line where is is being thrown is this one:

https://github.com/memspace/zefyr/blob/6f16dbfb7f1977dbaac1d7a65671ea2fb01ca334/packages/zefyr/lib/src/widgets/common.dart#L98

I would usually dismiss this error as one non trivial execution, but it happened too many times to be ignored on my user base, affecting more than 900 of my users in a short period. 

This is my sentry report screenshot for this issue:
![image](https://user-images.githubusercontent.com/1565421/50797148-1d923a80-12d4-11e9-8a11-911e8fbb6af4.png)

## Logs

```
NoSuchMethodError: NoSuchMethodError: The getter 'position' was called on null.
Receiver: null
Tried calling: position
  File "common.dart", line 95, in _RawZefyrLineState.bringIntoView
  File "common.dart", line 83, in _RawZefyrLineState.ensureVisible.<fn>
  File "binding.dart", line 990, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback
  File "binding.dart", line 938, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame
  File "binding.dart", line 842, in _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame
  File "zone.dart", line 1124, in _rootRun
  File "zone.dart", line 1021, in _CustomZone.run
  File "zone.dart", line 923, in _CustomZone.runGuarded
  File "hooks.dart", line 156, in _invoke
  File "hooks.dart", line 143, in _drawFrame
```

```
[✓] Flutter (Channel beta, v1.0.0, on Mac OS X 10.14.2 18C54, locale en-ES)
    • Flutter version 1.0.0 at /Users/panthro/flutter
    • Framework revision 5391447fae (6 weeks ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/panthro/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
```

**Comment by pulyaevskiy** [comment] 2019-01-08 20:06
Thanks for the report.

This looks critical. Wondering if you could provide a code sample or a reduced example of the mentioned layout with tab bar, especially if it reproduces the error.

I’ll take a look into this and will let you know if I find the cause asap.

**Comment by Panthro** [comment] 2019-01-08 20:12
I'll try to put together a reproducible example repo :-)

**Comment by pulyaevskiy** [comment] 2019-01-10 05:34
Short update: I did some experiments with zefyr in TabBar but couldn't reproduce the issue. I found a different one though, but that's unrelated.

Looking at the code I couldn't find where scrollable could be absent. Any code samples would be help a lot in investigating this further.

**Comment by Panthro** [comment] 2019-01-10 08:35
I haven't had time yet, but promise, will do :-)

**Comment by pulyaevskiy** [comment] 2019-01-28 22:10
Just an FYI that just released 0.3.1 contains some fixes for zefyr when used inside a tab bar.
It's unlikely that those changes will address your issue but I'd recommend to upgrade regardless.

**Comment by Panthro** [comment] 2019-01-29 14:36
Thanks for the update, I'm having a crazy couple of weeks thus couldn't
dedicate time to this.

But it is my todo list!

*Rafael Roman*

**Comment by pulyaevskiy** [comment] 2019-09-10 17:06
Any updates here? I'm considering to close this but wanted to check in with you first.

**Comment by pulyaevskiy** [comment] 2019-09-14 22:56
Closing this for now as resolved, but feel free to re-open if the issue is still not fixed on your end.

**Closed by pulyaevskiy** 2019-09-14 22:56 UTC
Labels: bug, waiting for response

**Comment by Panthro** [comment] 2019-10-30 15:29
Just as an update, I upgraded (after several months of no activity from my side) my app to newer versions of zefyr and the error stopped appearing.
