### ISSUE TITLE
error with  InputConnectionController currentTextEditingValue showAutocorrectionPromptRect

### ISSUE THREAD

**Issue by hason1** [memspace/zefyr#272] opened 2020-04-14 09:22 UTC
**Hello,

I did Pub get in pubspec and tried to run the zefyr package exemple project, when I try to run the project, the console shows the following errors, how to fix it ? this errors shows only if I try to use zefyr package**

Compiler message:
/C:/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.10.0/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - InputConnectionController.currentTextEditingValue
 - TextInputClient.showAutocorrectionPromptRect
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.10.0/lib/src/widgets/input.dart:23:24: Context: 'InputConnectionController.currentTextEditingValue' is defined here.
  TextEditingValue get currentTextEditingValue;
                       ^^^^^^^^^^^^^^^^^^^^^^^
/C:/FlutterSDK/flutter/packages/flutter/lib/src/services/text_input.dart:764:8: Context: 'TextInputClient.showAutocorrectionPromptRect' is defined here.
  void showAutocorrectionPromptRect(int start, int end);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Compiler message:
/C:/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.10.0/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - InputConnectionController.currentTextEditingValue
 - TextInputClient.showAutocorrectionPromptRect
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/FlutterSDK/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.10.0/lib/src/widgets/input.dart:23:24: Context: 'InputConnectionController.currentTextEditingValue' is defined here.
  TextEditingValue get currentTextEditingValue;
                       ^^^^^^^^^^^^^^^^^^^^^^^
/C:/FlutterSDK/flutter/packages/flutter/lib/src/services/text_input.dart:764:8: Context: 'TextInputClient.showAutocorrectionPromptRect' is defined here.
  void showAutocorrectionPromptRect(int start, int end);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\FlutterSDK\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 883

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\FlutterSDK\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 40s
Exception: Gradle task assembleDebug failed with exit code 1

----------------------------------------------
--------------------------------

**Here is my flutter doctor -v**

[√] Flutter (Channel dev, v1.18.0-dev.5.0, on Microsoft Windows [Version 10.0.18363.720], locale en-US)
    • Flutter version 1.18.0-dev.5.0 at C:\FlutterSDK\flutter
    • Framework revision 7f56b53de4 (2 days ago), 2020-04-12 12:00:01 -0400
    • Engine revision beb8a7ec48
    • Dart version 2.8.0 (build 2.8.0-dev.20.0 89b0f67261)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\mycomp\AppData\Local\Android\sdk
    • Platform android-R, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (1 available)

• No issues found!

**Comment by hason1** [comment] 2020-04-14 09:32
Here is another code which I used also, but it shows same errors messages:


import 'package:flutter/material.dart';
import 'package:zefyr/zefyr.dart';

class html_editor extends StatefulWidget {
  @override
  _html_editorState createState() => _html_editorState();
}

class _html_editorState extends State<html_editor> {
  ZefyrController controller;
  FocusNode focusNode;
  @override
  Widget build(BuildContext context) {


    final editor = ZefyrField(
      height: 200.0, // set the editor's height
      decoration: InputDecoration(labelText: 'Description'),
      controller: controller,
      focusNode: focusNode,
      autofocus: false,
      //imageDelegate: new CustomImageDelegate(),
      physics: ClampingScrollPhysics(),
    );


    final form = ListView(
      children: <Widget>[
        TextField(decoration: InputDecoration(labelText: 'Name')),
        editor,
        TextField(decoration: InputDecoration(labelText: 'Email')),
      ],
    );

    return Scaffold(
      resizeToAvoidBottomPadding: true,
      appBar: AppBar(title: Text('Example Form')),
      body: ZefyrScaffold(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: form,
        ),
      ),
    );
  }
}

**Comment by michinchin** [comment] 2020-05-27 20:52
The package currently follows the latest stable build of flutter. If you try to run the program with flutter master, dev, or beta you'll find this error

**Comment by cgestes** [comment] 2020-05-28 20:34
And the master of Zefyr follows master.

**Comment by dvkaush** [comment] 2020-09-26 14:24
Hi @michinchin , @cgestes 
I am getting exactly this issue too.

the output of my `flutter -version` command
```
Flutter 1.20.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fba99f6cf9 (12 days ago) • 2020-09-14 15:32:52 -0700
Engine • revision d1bc06f032
Tools • Dart 2.9.2
```

@hason1 any solution?

**Comment by dvkaush** [comment] 2020-09-26 14:41
I fixed issue according to this [comment](https://github.com/memspace/zefyr/issues/372#issuecomment-665085836)

duplicate of #372

**Closed** 2020-09-28 11:06 UTC
