### ISSUE TITLE
parsing json and save to json

### ISSUE THREAD

**Issue by edicybereye** [memspace/zefyr#52] opened 2018-12-09 09:21 UTC
Hi @pulyaevskiy ,

Please help me, how we save to format json and parsing fromJson on NotusDocument besause I try it someting wrong with my format
rror Parsing JSON: FormatException: Control character in string (at character 26)

from save I just do with jsonEncode and call document variable of NotesDocument and parsing with jsondecode and NotusDocument.fromJson

**Comment by pulyaevskiy** [comment] 2018-12-11 18:41
Hi,

Could you provide a sample code snippet so that it's more clear to me what is going on? Also a sample JSON encoded document would help too. From the error message you gave it looks like you have an issue in your JSON encoded string.

**Comment by edicybereye** [comment] 2018-12-11 18:45
Hi Thanks for your response.. I have handle and resolved with replace \n
with \\n and problem solved.. now just looking for replace (") because if
user writing with (") that will be broken the format and show json format
on NotusDocument

**Comment by pulyaevskiy** [comment] 2018-12-11 19:04
This is unexpected. `jsonEncode` should escape `\n` and quotes automatically. Are you constructing your source JSON manually?

**Comment by edicybereye** [comment] 2018-12-11 19:08
Nope, I do with jsonEncode(document.tojson) of notusdocument,

Please refer on attachment

**Comment by akaisa** [comment] 2018-12-13 12:44
Hi @pulyaevskiy  I just forward problem from @edicybereye 
  submit() async {
    NotusDocument _data = _controller.document;
    final response = await http.post(BaseUrl.simpanBABBuku, body: {
      "idBuku": widget.models.id,
      "idUsers": idUsers,
      "isi": json.encode(_data.toJson()),
      "status": "0"
    });
    final data = jsonDecode(response.body);
    int value = data['value'];
    if (value == 1) {
      setState(() {
        Navigator.pop(context);
      });
    } else {
      print("Problem");
    }
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    getPref();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: Colors.black,
        elevation: 0.0,
        leading: IconButton(
          onPressed: () {
            Navigator.pop(context);
          },
          icon: Icon(
            Icons.close,
            color: Colors.white,
          ),
        ),
        actions: <Widget>[
          IconButton(
            onPressed: () {
              submit();
            },
            icon: Icon(
              Icons.send,
              color: Colors.white,
            ),
          )
        ],
        title: Text(
          widget.models.namaBuku,
          style: TextStyle(
            color: Colors.white,
          ),
        ),
      ),
      backgroundColor: Colors.white,
      body: ZefyrScaffold(
        child: ZefyrEditor(
          controller: _controller,
          focusNode: _focusNode,
          autofocus: true,
        ),
      ),
    );
  }
}

**Comment by pulyaevskiy** [comment] 2018-12-13 18:13
I'm afraid I can't reproduce this behavior on my end.
There is also a test case for json serialization, which works:
https://github.com/memspace/zefyr/blob/00d295d7c3a139f43c426bc69affb320279c6161/packages/notus/test/document_test.dart#L46-L52

Is there a way you can provide an example document content (as Delta preferably but plain text or json would work as well)? This might help.

**Comment by pulyaevskiy** [comment] 2018-12-15 04:43
Is this still an issue @edicybereye ?

**Comment by edicybereye** [comment] 2018-12-18 15:20
Hi @pulyaevskiy , are you have personal email, because I want send capture json format

**Comment by pulyaevskiy** [comment] 2018-12-20 19:13
@edicybereye you can find it in [pubspec.yaml](https://github.com/memspace/zefyr/blob/master/packages/zefyr/pubspec.yaml) or on [Pub](https://pub.dartlang.org/packages/zefyr) (see sidebar with author details).

**Comment by pulyaevskiy** [comment] 2019-09-14 22:57
Closing this. You can refer to updated Quick Start tutorial which shows how to load and save documents from/to JSON: https://zefyr-editor.gitbook.io/docs/v/v0.8.0/quick-start .

**Closed by pulyaevskiy** 2019-09-14 22:57 UTC
