### ISSUE TITLE
What about adding FloatingCursor support for iOS?

### ISSUE THREAD

**Issue by amantoux** [memspace/zefyr#303] opened 2020-05-17 07:09 UTC
Shouldn't we support this functionality? as per https://github.com/flutter/flutter/pull/25384

**Comment by britannio** [comment] 2020-07-22 10:45
duplicate of https://github.com/memspace/zefyr/issues/240, still something I'd like to see though.

**Comment by pulyaevskiy** [comment] 2020-09-04 19:29
Closing as duplicate of #240.

**Closed by pulyaevskiy** 2020-09-04 19:29 UTC
