### ISSUE TITLE
Is it still being updated?

### ISSUE THREAD

**Issue by ArthurKnight** [memspace/zefyr#140] opened 2019-08-18 02:04 UTC
Could you update the version of image_picker plugin.
your plugin depends on image_picker ^0.5.0, image_picker ^0.5.0 is required.
but the newest version of image_picker is ^0.6.1+3. it fix many bugs.can you upgade the dependency .thank you .

**Comment by pulyaevskiy** [comment] 2019-08-18 03:57
Looks like duplicate of #137, closing this one, will update the other issue.

**Closed by pulyaevskiy** 2019-08-18 03:57 UTC
Labels: duplicate
