### ISSUE TITLE
How can I show the content with other widget?

### ISSUE THREAD

**Issue by Hanggi** [memspace/zefyr#60] opened 2018-12-22 00:58 UTC
After edit the content with zefyr editor, I got a Delta string.

Then I need show the content in my custom page, not full page, not in a textfield, just in a custom scrollview with any other widgets. but I can not find any function to show the content.

**Comment by pulyaevskiy** [comment] 2018-12-22 01:04
This looks like maybe a duplicate of #26 . Feel free to 👍 that issue if I understood it correctly.
I'm planning to add a new widget `ZefyrView` to cover this use case. Stay tuned for updates in coming weeks.

**Comment by Hanggi** [comment] 2018-12-22 01:35
@pulyaevskiy yes, it is. And do you have some certain schedule? So that I can make a plan.

Thank you.

**Comment by pulyaevskiy** [comment] 2018-12-22 17:50
@Hanggi I don't have a schedule unfortunately. I may get to this in a week or it may take longer.
Make sure to subscribe to #26 as I will be posting updates there.

I can say that I'll be looking into this issue today and tomorrow, but can't promise it'll be done.

**Comment by pulyaevskiy** [comment] 2018-12-22 18:39
Closing this as duplicate of #26.

**Closed by pulyaevskiy** 2018-12-22 18:39 UTC
Labels: duplicate
