### ISSUE TITLE
hintText does not at the start of the editor

### ISSUE THREAD

**Issue by wuyugege** [memspace/zefyr#152] opened 2019-09-03 15:18 UTC
the code is here:
`

    return ZefyrScaffold(
      child: Container(
        padding: EdgeInsets.all(16),
        color: Colors.white,
        child: ListView(
          children: <Widget>[
            Container(
                child: TextFormField(
              controller: _titleController,
              decoration: InputDecoration(hintText: '请输入标题'),
            )),
            ZefyrTheme(
              data: theme,
              child: ZefyrField(
                height: 500,
                decoration: InputDecoration(
                  border: InputBorder.none,
                  hintText: '请输入正文',
                ),
                controller: _contentController,
                focusNode: _contentFocusNode,
                //imageDelegate: new CustomImageDelegate(),
              ),
            ),
          ],
        ),
      ),
    );
  }`
the result is here :
![image](https://user-images.githubusercontent.com/11754341/64186265-1e9a5c80-cea1-11e9-8c62-bcdbd31518ff.png)

**Comment by pulyaevskiy** [comment] 2019-09-14 22:24
Closing this is a duplicate of #163 . Please follow discussion there.

**Closed by pulyaevskiy** 2019-09-14 22:24 UTC
