### ISSUE TITLE
Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:  - 'updateFloatingCursor'

### ISSUE THREAD

**Issue by msomda** [memspace/zefyr#77] opened 2019-01-31 01:52 UTC
## Steps to Reproduce

Zefyr is generating the ERROR below after the latest Flutter/Dart upgrade!

## Logs

Compiler message:
file:///C:/Users/Magus/flutter/.pub-cache/hosted/pub.dartlang.org/zefyr-0.3.1/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - 'updateFloatingCursor'
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
file:///C:/Users/Magus/flutter/packages/flutter/lib/src/services/text_input.dart:605:8: Context: 'updateFloatingCursor' is defined here.
  void updateFloatingCursor(RawFloatingCursorPoint point);
       ^^^^^^^^^^^^^^^^^^^^
Compiler failed on C:\Users\Magus\AndroidStudioProjects\flutter_projects\persona\lib\main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

Flutter Doctor

C:\Users\Magus\flutter\bin\flutter.bat doctor --verbose
[√] Flutter (Channel beta, v1.1.8, on Microsoft Windows [Version 10.0.17763.292], locale en-CA)
    • Flutter version 1.1.8 at C:\Users\Magus\flutter
    • Framework revision 985ccb6d14 (3 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at C:\Users\Magus\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[√] Android Studio (version 3.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[√] IntelliJ IDEA Community Edition (version 2018.2)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2018.2.5
    • Flutter plugin version 30.0.2
    • Dart plugin version 182.4892.25

[√] VS Code, 64-bit edition (version 1.30.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 2.21.1

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!
Process finished with exit code 0

**Comment by pulyaevskiy** [comment] 2019-01-31 01:55
This looks like a duplicate of #58.
Note: published versions of Zefyr only expected to work with stable version of Flutter, other channels are not guaranteed.

For solution see https://github.com/memspace/zefyr/issues/58#issuecomment-449586072.

**Closed by pulyaevskiy** 2019-01-31 01:55 UTC

**Comment by abhee4** [comment] 2020-01-05 13:15
Hi @pulyaevskiy, 
Getting error on InputConnectionController

**Logs:**
```
Launching lib\main.dart on Pixel 3 in debug mode...

Compiler message:
/C:/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/input.dart:11:7: Error: The non-abstract class 'InputConnectionController' is missing implementations for these members:
 - TextInputClient.connectionClosed
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class InputConnectionController implements TextInputClient {
      ^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:661:8: Context: 'TextInputClient.connectionClosed' is defined here.
  void connectionClosed();
       ^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/selection.dart:42:7: Error: The non-abstract class '_ZefyrSelectionOverlayState' is missing implementations for these members:
 - TextSelectionDelegate.copyEnabled
 - TextSelectionDelegate.cutEnabled
 - TextSelectionDelegate.pasteEnabled
 - TextSelectionDelegate.selectAllEnabled
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.
class _ZefyrSelectionOverlayState extends State<ZefyrSelectionOverlay>
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:630:12: Context: 'TextSelectionDelegate.copyEnabled' is defined here.
  bool get copyEnabled => true;
           ^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:627:12: Context: 'TextSelectionDelegate.cutEnabled' is defined here.
  bool get cutEnabled => true;
           ^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:633:12: Context: 'TextSelectionDelegate.pasteEnabled' is defined here.
  bool get pasteEnabled => true;
           ^^^^^^^^^^^^
/C:/flutter/packages/flutter/lib/src/services/text_input.dart:636:12: Context: 'TextSelectionDelegate.selectAllEnabled' is defined here.
  bool get selectAllEnabled => true;
           ^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/rich_text.dart:184:26: Error: The parameter 'value' of the method 'RenderZefyrParagraph.text' has type 'TextSpan', which does not match the corresponding type, 'InlineSpan', in the overridden method, 'RenderParagraph.text'.
 - 'TextSpan' is from 'package:flutter/src/painting/text_span.dart' ('/C:/flutter/packages/flutter/lib/src/painting/text_span.dart').
 - 'InlineSpan' is from 'package:flutter/src/painting/inline_span.dart' ('/C:/flutter/packages/flutter/lib/src/painting/inline_span.dart').
Change to a supertype of 'InlineSpan', or, for a covariant parameter, a subtype.
  void set text(TextSpan value) {
                         ^
/C:/flutter/packages/flutter/lib/src/rendering/paragraph.dart:115:7: Context: This is the overridden method ('text').
  set text(InlineSpan value) {
      ^
/C:/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/editable_text.dart:102:28: Error: The method 'reparentIfNeeded' isn't defined for the class 'FocusScopeNode'.
 - 'FocusScopeNode' is from 'package:flutter/src/widgets/focus_manager.dart' ('/C:/flutter/packages/flutter/lib/src/widgets/focus_manager.dart').
Try correcting the name to the name of an existing method, or defining a method named 'reparentIfNeeded'.
    FocusScope.of(context).reparentIfNeeded(focusNode);
                           ^^^^^^^^^^^^^^^^
/C:/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/selection.dart:483:22: Error: Too few positional arguments: 6 required, 4 given.
        .buildToolbar(context, editingRegion, midpoint, widget.delegate);
                     ^
/C:/flutter/.pub-cache/git/zefyr-3be80cf9c24abb0388daaf0baaad28a2c09f5220/packages/zefyr/lib/src/widgets/input.dart:153:18: Error: The argument type 'String' can't be assigned to the parameter type 'DiagnosticsNode'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('/C:/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
        context: 'while updating editing value',
                 ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

```
> BUILD FAILED in 8s
> Gradle task assembleDebug failed with exit code 1
> Exited (sigterm)

**pubspec.yaml**
```
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr
      ref: flutter-master
```


```
$ flutter doctor -v
[√] Flutter (Channel beta, v1.12.13+hotfix.6, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.12.13+hotfix.6 at C:\flutter
    • Framework revision 18cd7a3601 (4 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\abheedevta\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 3.5)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b03)

[√] VS Code (version 1.41.1)
    • VS Code at C:\Users\abheedevta\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.7.1

[√] Connected device (4 available)
    • MI MAX     • xxxxxxxx          • android-arm64  • Android 7.0 (API 24)
    • Pixel 3    • 192.168.1.xxx:5555 • android-arm64  • Android 10 (API 29)
    • Chrome     • chrome            • web-javascript • Google Chrome 79.0.3945.88
    • Web Server • web-server        • web-javascript • Flutter Tools

• No issues found!
```

Please help !!!

**Comment by pulyaevskiy** [comment] 2020-01-10 19:14
I’d recommend to switch to stable channel of flutter since it’s the only one supported right now.

**Comment by jims57** [comment] 2020-07-28 09:24
@pulyaevskiy the **Zefyr** Editor doesn't support **master** branch of Flutter? I am using **master**. thanks.
