### ISSUE TITLE
type 'StatefulElement' is not a subtype of type 'Widget'

### ISSUE THREAD

**Issue by artashsanoyan** [memspace/zefyr#130] opened 2019-07-30 07:01 UTC
## Steps to Reproduce

1. Create new flutter project 
2. Install last version of zefyr (0.6.0 at this moment)
3. open main.dart file and insert following code into it 

```
import 'package:flutter/material.dart';
import 'package:zefyr/zefyr.dart';

void main() => runApp(InitApp());

class InitApp extends StatelessWidget {
  @override
  Widget build(context) {
    return MaterialApp(home: Home());
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  static ZefyrController _controller;
  static final _focusNode = FocusNode();

  bool x = true;

  @override
  void initState() {
    super.initState();
    final document = NotusDocument();
    _controller = ZefyrController(document);
  }

  @override
  Widget build(context) {
    return Scaffold(
      appBar: AppBar(title: Text('Home')),
      body: ZefyrScaffold(
        child: ZefyrField(
          controller: _controller,
          focusNode: _focusNode,
        ),
      ),
    );
  }

  void dispose() {
    _controller.dispose();
    super.dispose();
  }
}
```

## Logs

```
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following assertion was thrown building ZefyrScaffold(dirty, state: ZefyrScaffoldState#456ed):
flutter: type 'StatefulElement' is not a subtype of type 'Widget'
flutter:
flutter: Either the assertion indicates an error in the framework itself, or we should provide substantially
flutter: more information in this error message to help you determine and fix the underlying cause.
flutter: In either case, please report this assertion by filing a bug on GitHub:
flutter:   https://github.com/flutter/flutter/issues/new?template=BUG.md
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      ZefyrScaffoldState.build 
package:zefyr/…/widgets/scaffold.dart:43
flutter: #1      StatefulElement.build 
package:flutter/…/widgets/framework.dart:4012
flutter: #2      ComponentElement.performRebuild 
package:flutter/…/widgets/framework.dart:3924
flutter: #3      Element.rebuild 
package:flutter/…/widgets/framework.dart:3721
flutter: #4      BuildOwner.buildScope 
package:flutter/…/widgets/framework.dart:2340
flutter: #5      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame 
package:flutter/…/widgets/binding.dart:700
flutter: #6      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback 
package:flutter/…/rendering/binding.dart:285
flutter: #7      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback 
package:flutter/…/scheduler/binding.dart:1016
flutter: #8      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame 
package:flutter/…/scheduler/binding.dart:958
flutter: #9      _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame 
package:flutter/…/scheduler/binding.dart:874
flutter: #13     _invoke  (dart:ui/hooks.dart:236:10)
flutter: #14     _drawFrame  (dart:ui/hooks.dart:194:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: Another exception was thrown: setState() or markNeedsBuild() called when widget tree was locked.
```

```
flutter doctor -v
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Mac OS X 10.14.6 18G84, locale en-AM)
    • Flutter version 1.7.8+hotfix.4 at /usr/local/flutter
    • Framework revision 20e59316b8 (11 days ago), 2019-07-18 20:04:33 -0700
    • Engine revision fee001c93f
    • Dart version 2.4.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/artashes/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/artashes/Library/Android/sdk
    • Java binary at: /Library/Java/Home/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.3, Build version 10G8
    • CocoaPods version 1.7.5

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/setup/#android-setup for detailed instructions).

[✓] VS Code (version 1.36.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (1 available)
    • iPhone Xʀ • FB630D4D-F695-4B10-A0DF-F0FAF895720D • ios • com.apple.CoreSimulator.SimRuntime.iOS-12-4 (simulator)

! Doctor found issues in 1 category.
```

**Comment by pulyaevskiy** [comment] 2019-09-04 04:01
I'm not able to reproduce this error using provided code. Wondering if this has been resolved for you?

**Comment by pulyaevskiy** [comment] 2019-09-14 22:38
Closing this for now, feel free to re-open if the issue is still not resolved for you.

**Closed by pulyaevskiy** 2019-09-14 22:38 UTC
Labels: waiting for response
