### ISSUE TITLE
hintText show in widget bottom，how to set show in top like textfield？thanks！

### ISSUE THREAD

**Issue by linguitang** [memspace/zefyr#93] opened 2019-03-24 12:10 UTC
rt

**Comment by 451518849** [comment] 2019-04-25 09:57
@linguitang Have you solved it yet？

**Comment by linguitang** [comment] 2019-04-25 12:24
@451518849 no

**Comment by pulyaevskiy** [comment] 2019-09-14 22:51
Closing this as duplicate of #163 . Please follow discussion there.

**Closed by pulyaevskiy** 2019-09-14 22:51 UTC
