### ISSUE TITLE
Change bold and italic to toggle on/off

### ISSUE THREAD

**Issue by stemuk** [memspace/zefyr#20] opened 2018-08-10 17:02 UTC
I would suggest to change the bold and italic text style buttons to toggle their respective styles on or off for all following entries. 

The current implementation only allows for changing currently marked text to bold/italic, it however makes things very complicated if you mark your last typed text as bold/italic, since this means that all following text is automatically marked as bold or italic without the simple option to turn it off again.

IMHO the option to mark selected text as bold or italic should be kept, if no text is currently selected however the respective buttons should toggle the text styles on/off as described above.

**Comment by pulyaevskiy** [comment] 2018-08-14 06:48
If I understand this correctly this issue is about toggling inline style(s) with collapsed selection, right?
E.g. when selected range is zero and we see caret at specific position.

So toggling inline style at caret position **will** affect style of all characters inserted later by the user.

Why I prefer to phrase it this way is because this operation is not a document change, there is no character style to change when toggling with collapsed selection.

Also, current behavior IS a toggle on/off, it just works for non-empty selection. I'll update the title to reflect this.

This would probably have to be implemented as an extension to existing heuristic rules since we need to keep this information somewhere outside of the document model.

**Comment by stemuk** [comment] 2018-08-14 21:08
My mistake, I should have labeled this as a possible bug and cross-tested this issue on iOS. 
At the moment if you use the bold or italic buttons and no text is marked on Android, nothing happens and the text that gets entered after the button press does not change its style. So if I understand the behaviour you layed out above correctly, the current behaviour on Android is in fact a bug and not the expected behaviour. The source of this bug might again be the GBoard or maybe it is just an Android specific flutter issue.

If you have troubles reproducing the issue I could recod some footage of the bug since no errors are thrown.

**Comment by stemuk** [comment] 2018-08-27 08:02
Did you have success recreating the issue on Android so far? If not I could provide footage of the issue or a Stacktrace if that helps fixing it.

**Comment by pulyaevskiy** [comment] 2018-08-29 17:04
Haven't had a chance to look into this in the past two weeks.

It would definitely help if you can provide more details here so feel free to add as much as you can!

**Comment by stemuk** [comment] 2018-10-05 19:51
@pulyaevskiy Did the recorded footage help replicating the issues described above? To me it seems like the issues mainly appear on Android since the iOS keyboard does not seem to have the same behavior when it comes to auto-correcting text. 
Please let me know if I can help in any way.

**Comment by pulyaevskiy** [comment] 2018-10-06 17:43
@stemuk Hey, sorry for being slow here.

I haven't been able to spend much time on these, but videos are incredibly helpful, really appreciate your time!

Divider issue: this should be fixed in the latest master. I haven't published an updated version yet though. See 19da3daec409059954ce9fd480821673c8168cf9 for details.

Bold/italic issue: I think I agree with your points. I have a rough idea on how to implement this, just need to get some actual time.

Android autocomplete issue: I still need to do more debugging on this one, not much I can say at the moment. I'll do another run on this one today/tomorrow though.

**Comment by pulyaevskiy** [comment] 2018-10-06 21:33
I just pushed an update to master which should solve the "autocorrect" issue on Android.

You should be able to test it by configuring dependency overrides in your pubspec:

```yaml
dependency_overrides:
  zefyr:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/zefyr
  notus:
    git:
      url: https://github.com/memspace/zefyr.git
      path: packages/notus
```

Let me know if this works for you. I'll probably publish a new version with these changes if all looks good.

**Comment by stemuk** [comment] 2018-10-10 16:19
@pulyaevskiy I updated my previous comment with some footage and added some comments. Please let me know what you think!

**Comment by stemuk** [comment] 2018-10-10 23:41
@pulyaevskiy Thanks again for your fast response! As for the expected behaviour around deleting a divider:

The way I see it, this https://streamable.com/eb34s clip describes unintuitive behaviour in the way that even though my cursor was in the last line of the document, multiple presses of the back button did not delete the divider above my cursor. 
(Edit: I just watched the clip again and it might be that a bug caused the cursor to be squeezed into the same line as the divider even though the cursor is beneath it, since putting the cursor manually into the line below the divider makes the cursor-divider distance much larger...)

Since taps are visualized in this video, notice how I tapped the back button multiple times near the end of the clip without being able to delete the divider.

I just recorded an extended clip https://streamable.com/vmdf3 that both shows the expected behaviour which seems to be prevalent if you create a divider in between already created (empty) lines and the unintuitive behaviour I layed out which occurs if you create a divider at the last line (bottom) of your document. 

Since this is likely a place where most editing (and divider-creation) will occur I believe that this behaviour should be changed in order to be consistent with the behaviour you mentioned (a simple back-button press should delete the freshly created divider instead of blocking all deletions unless the cursors position is changed).

**Comment by pulyaevskiy** [comment] 2018-10-10 23:59
OK, I think I'm starting to see where your confusion comes from.

As I mentioned in my previous comment when there are empty lines before a divider pressing backspace removes those empty lines. However when you added "Just a test" on a line right before a divider it results in a no-op action. This is because divider can not be merged with the text above it.

Now, _I think_ I have a solution for this case. Which is instead of current no-op behavior we can make the divider selected when user taps on `backspace` (so that it appears with selection background and handles). So next time user taps on `backspace` the divider is gone.

How does this sound?

Also note that you can move caret by tapping on the left or right side of a divider (works with images as well). If you tap on the right side the caret would move past the divider so you can now delete it by tapping on `backspace`.

I see a few separate issues that can be addressed here:

1. When divider is inserted position caret after it, not before as it currently does. This would make deletion a bit easier. And looks like would mostly satisfy your scenario.
2. When user attempts to delete a line break before a divider and previous line is not empty make the divider selected instead of defaulting to no-op. This could have edge cases when previous line contains another embed (image) and I feel like in this case it would be more accurate to select embed from the previous line.

**Comment by pulyaevskiy** [comment] 2018-10-11 00:00
Great discussion, by the way. Thanks again for tracking down this issues.

**Comment by stemuk** [comment] 2018-10-11 10:05
@pulyaevskiy Thanks a lot for the quick fix, I think your solution works really well. As for the pasteButtonLabel:
I recorded all the footage above in the zefyr editor example to make reproduction easier, which is why I would suspect that the pasteButtonLabel is not in the app itself.

If I recall correctly you mentioned in another issue that you are currently using the build-in flutter labels for Copy, Cut and Paste operations and not custom ones.

**Comment by pulyaevskiy** [comment] 2018-10-12 17:30
@stemuk yeah, thanks! You are right.

Strange though I couldn't reproduce it on emulator. Wondering which locale gets initialized on your end for the app?

**Comment by stemuk** [comment] 2018-10-12 18:20
@pulyaevskiy My locale is German, but I just cross checked and the issue can be reproduced in English and French as well, which would suggest that it is not locale exclusive.

**Comment by stemuk** [comment] 2018-10-16 10:53
@pulyaevskiy It seems there is a patch coming soon that might address this issue: https://github.com/flutter/flutter/issues/22624

**Comment by pulyaevskiy** [comment] 2018-10-16 20:33
Nice find, this would explain why I couldn't reproduce it on my end (different Flutter versions).

**Comment by pulyaevskiy** [comment] 2018-10-20 22:55
Awesome, thanks for confirming!
Please stay tuned for the remaining fix. I'm trying my best to get some time for this.

**Comment by kolja-esders** [comment] 2019-04-30 19:29
Any update on the underlying issue of allowing toggling of bold/italic attributes @pulyaevskiy? Would be greatly appreciated!

**Closed** 2019-09-24 03:58 UTC
