### ISSUE TITLE
Is there a way to choose which tools appear in the toolbar?

### ISSUE THREAD

**Issue by gilgold** [memspace/zefyr#62] opened 2018-12-26 06:01 UTC
Hello!
Is there an option to choose which tools to include in the toolbar? (out of the existing tools)

**Comment by pulyaevskiy** [comment] 2018-12-30 01:51
Hi, this is not possible at the moment, but is pretty high in priority list.
Closing as duplicate of #23 . Make sure to 👍 the other issue.

**Closed by pulyaevskiy** 2018-12-30 01:51 UTC
