### ISSUE TITLE
Example doesn't implement TextInputClient.updateFloatingCursor

### ISSUE THREAD

**Issue by lukepighetti** [memspace/zefyr#87] opened 2019-03-05 12:42 UTC
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v1.3.2, on Mac OS X 10.14.3 18D109, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
[✓] Android Studio (version 3.1)
[✓] VS Code (version 1.31.1)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by pulyaevskiy** [comment] 2019-03-10 06:05
Closing as duplicate of #86 . There is now new version of zefyr (0.5.0) which fixes this issue.

**Closed by pulyaevskiy** 2019-03-10 06:05 UTC
